# |  (C) 2008-2025 Potsdam Institute for Climate Impact Research (PIK)
# |  authors, and contributors see CITATION.cff file. This file is part
# |  of MAgPIE and licensed under AGPL-3.0-or-later. Under Section 7 of
# |  AGPL-3.0, you are granted additional permissions described in the
# |  MAgPIE License Exception, version 1.0 (see LICENSE file).
# |  Contact: magpie@pik-potsdam.de

# ----------------------------------------------------------
# description: Global Ref2050 and GHG2050 scenarios
# ----------------------------------------------------------

library(gms)
library(lucode2)
library(magclass)

source("scripts/start_functions.R")
source("config/default.cfg")

cfg$info$flag <- "GlobalLandUse"
cfg$results_folder <- "output/:title:"
cfg$results_folder_highres <- "output"
cfg$force_replace <- TRUE
cfg$force_download <- FALSE
cfg$sequential <- TRUE
cfg$gms$c_timesteps <- "5year2050"

cfg$output <- c(
  "output_check",
  "extra/disaggregation",
  "rds_report",
  "extra/reportMAgPIE2SEALS"
)

cfg$gms$peatland <- "v2"
cfg$gms$s58_fix_peatland <- 2020
cfg$gms$s58_annual_rewetting_limit <- 0.02
cfg$gms$s58_rewetting_exo <- 0
cfg$gms$s58_rewetting_exo_noselect <- 0
cfg$gms$s58_intact_prot_exo <- 0
cfg$gms$s58_intact_prot_exo_noselect <- 0

cfg <- setScenario(cfg, c("SSP2", "NPI"))

cfg$gms$s56_minimum_cprice <- 0
cfg$gms$s56_c_price_induced_aff <- 0
cfg$gms$c56_mute_ghgprices_until <- "y2025"
cfg$gms$c56_emis_policy <- "all"

cfg$gms$c12_interest_rate <- "gdp_dependent"
cfg$gms$s15_elastic_demand <- 1
cfg$gms$c60_biodem_level <- 0
cfg$gms$s80_optfile <- 1

cfg$repositories <- append(
  list(
    "https://rse.pik-potsdam.de/data/magpie/public" = NULL,
    "./patch_inputdata" = NULL
  ),
  getOption("magpie_repos")
)

write_global_ghg_prices <- function() {
  base_prices <- read.magpie("modules/56_ghg_policy/input/f56_pollutant_prices.cs3")
  base_prices <- collapseNames(base_prices[, , getNames(base_prices, dim = 2)[1]])
  base_prices[, , ] <- 0

  years <- c(seq(1995, 2025, by = 5), 2050, 2100, 2150)
  price400 <- new.magpie(getRegions(base_prices), years, getNames(base_prices), fill = 0)
  price400[, "y2050", "co2_c"] <- 400
  price400[, "y2100", "co2_c"] <- 400
  price400[, "y2150", "co2_c"] <- 400
  price400 <- time_interpolate(price400, seq(1995, 2150, by = 5), TRUE)
  price400[, , "ch4"] <- price400[, , "co2_c"] * 28
  price400[, , "n2o_n_direct"] <- price400[, , "co2_c"] * 265 * 44 / 28
  price400[, , "n2o_n_indirect"] <- price400[, , "co2_c"] * 265 * 44 / 28
  price400[, , "co2_c"] <- price400[, , "co2_c"] * 44 / 12

  patched_prices <- mbind(
    add_dimension(base_prices, dim = 3.2, add = "scen", nm = "T0-GHG"),
    add_dimension(price400, dim = 3.2, add = "scen", nm = "T400-GHG")
  )

  patch_dir <- file.path("patch_inputdata", "global_ghg_prices")
  if (dir.exists(patch_dir)) {
    unlink(patch_dir, recursive = TRUE)
  }
  dir.create(patch_dir, recursive = TRUE)
  write.magpie(patched_prices, file.path(patch_dir, "f56_pollutant_prices.cs3"))
  tardir(patch_dir, file.path("patch_inputdata", "global_ghg_prices.tgz"))
  unlink(patch_dir, recursive = TRUE)
}

download_and_update(cfg)
write_global_ghg_prices()
cfg$input["zz_global_ghg_prices"] <- "global_ghg_prices.tgz"

run_global_scenario <- function(title, pollutant_prices, second_gen_biodem,
                                rewetting_switch) {
  cfg$title <- title
  cfg$gms$c56_pollutant_prices <- pollutant_prices
  cfg$gms$c56_pollutant_prices_noselect <- "T0-GHG"
  cfg$gms$c60_2ndgen_biodem <- second_gen_biodem
  cfg$gms$c60_2ndgen_biodem_noselect <- second_gen_biodem
  cfg$gms$s58_rewetting_switch <- rewetting_switch
  start_run(cfg, codeCheck = FALSE)
}

# Base2020 in the source study is the ESA 2020 land-cover map and is not
# generated by MAgPIE. The MAgPIE-generated scenarios are Ref2050 and GHG2050.
run_global_scenario(
  title = "Global_Ref2050",
  pollutant_prices = "T0-GHG",
  second_gen_biodem = "SSPDB-SSP2-Ref-REMIND-MAGPIE",
  rewetting_switch = 0
)

run_global_scenario(
  title = "Global_GHG2050",
  pollutant_prices = "T400-GHG",
  second_gen_biodem = "SSPDB-SSP2-26-REMIND-MAGPIE",
  rewetting_switch = Inf
)
